### ISSUE TITLE
Console on VE.Direct should be CCGX-only option

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1265] opened 2024-06-20 06:58 UTC
1) Only the CCGX had UART on VE.Direct, so the "Console" setting under VE.Direct should be hidden on non-CCGX devices like Ekrano.
2) Attempting to enable the "Console" setting on a CCGX did not work.

**Comment by chriadam** [comment] 2024-06-20 07:04
Marking as low priority, not for 1.0.0

**Comment by ReinvdZee** [comment] 2024-06-21 11:27
Duplicate of https://github.com/victronenergy/gui-v2/issues/1247

**Closed** 2024-06-21 11:28 UTC
Labels: low_prio
