### ISSUE TITLE
gui-v2 (wasm) throws runtime error on repeated connection attempts

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1177] opened 2024-05-31 12:43 UTC
I am seeing runtime error when trying to launch gui-v2 (wasm) on the latest main branch, possibly from [Add BackendConnection::serviceUidFromName()](https://github.com/victronenergy/gui-v2/commit/f8eca734b84a5c9f2c95c866e78d9be0c16bf11d) change.

```
venus-gui-v2.js:1715 BackendConnection state: Victron::VenusOS::BackendConnection::Connecting
Uncaught RuntimeError: null function or function signature mismatch
    at QGuiApplication::notify(:6931/QObject*, QEvent*) (http://localhost:6931/venus-gui-v2.wasm)
    at QCoreApplication::notifyInternal2(:6931/QObject*, QEvent*) (http://localhost:6931/venus-gui-v2.wasm)
    at QCoreApplicationPrivate::sendPostedEvents(:6931/QObject*, int, QThreadData*) (http://localhost:6931/venus-gui-v2.wasm)
    at QCoreApplication::sendPostedEvents(:6931/QObject*, int) (http://localhost:6931/venus-gui-v2.wasm)
    at QEventDispatcherWasm::processPostedEvents(:6931/) (http://localhost:6931/venus-gui-v2.wasm)
    at QWasmEventDispatcher::processPostedEvents(:6931/) (http://localhost:6931/venus-gui-v2.wasm)
    at std::__2::__function::__func<QEventDispatcherWasm::wakeUp(:6931/)::$_0, std::__2::allocator<QEventDispatcherWasm::wakeUp()::$_0>, void ()>::operator()() (http://localhost:6931/venus-gui-v2.wasm)
    at (:6931/anonymous namespace)::trampoline(void*)::$_0::__invoke(void*) (http://localhost:6931/venus-gui-v2.wasm)
    at wrapper (venus-gui-v2.js:10243:32)
    at callUserCallback (venus-gui-v2.js:7069:9)
```

**Comment by DanielMcInnes** [comment] 2024-06-02 23:39
@jpetrell  is this repeateable for you? I can't reproduce it locally.

**Comment by jpetrell** [comment] 2024-06-03 09:36
Ok false alarm, had VRM two-way communication disabled for some reason. The error seems real real, but should not happen during the normal usage, only if repeated connection attempts fail.

> @jpetrell is this repeatable for you? I can't reproduce it locally.

Thanks for testing! That is really helpful, prompted me to go back and re-check my configs. :smile:

**Comment by blammit** [comment] 2024-11-25 05:30
Discussed with @chriadam , this should be fixed now.

**Closed by blammit** 2024-11-25 05:30 UTC
Labels: low_prio
