### ISSUE TITLE
Missing Grid in GUI 2

### ISSUE THREAD

**Issue by tmonxx** [victronenergy/gui-v2#1679] opened 2024-11-01 13:17 UTC
Hi.

After switching to GUI 2 our Grid is shown as diconnected.
The System is running on Cerbo GX device.
GUI 1 is ok.
Any ideas?
![IMG_0903](https://github.com/user-attachments/assets/70c38095-9c63-4023-9660-97be7e3dce26)
![IMG_0904](https://github.com/user-attachments/assets/e3a5447a-95b7-482d-b295-b5d47767dc91)

**Comment by blammit** [comment] 2024-11-03 23:30
Sounds like the same issue as https://github.com/victronenergy/gui-v2/issues/1626.

If you could add victron.vrm@qinetic.com.au to the users for your VRM installation, I can verify whether my patch fixes the issue for you.

**Comment by tmonxx** [comment] 2024-11-04 19:42
> Klingt nach dem gleichen Problem wie #1626 .
> 
> Wenn Sie victron.vrm (at) qinetic.com.au zu den Benutzern für Ihre VRM-Installation hinzufügen könnten, kann ich überprüfen, ob mein Patch das Problem für Sie behebt.

Thank You. You are in…

**Comment by blammit** [comment] 2024-11-07 22:19
Danke schön, I tested the https://github.com/victronenergy/gui-v2/issues/1626 fixes on this installation, and the issue is fixed now. The changes were released with VenusOS v3.52~2.

**Closed by blammit** 2024-11-07 22:19 UTC

**Comment by tmonxx** [comment] 2024-11-08 07:31
Thank You for Your help.
