### ISSUE TITLE
GUI v2 stuck in rebooting screen

### ISSUE THREAD

**Issue by wetty** [victronenergy/gui-v2#1447] opened 2024-09-08 11:20 UTC
I am running venus Os 3.50-20 on a Raspberry 3+

Since a few versions the GUI v2 is always showing the following screen. Rebooting or updating to a newer Venus OS does not change ist. Tested with several Browsers on several machines (MAC and PC). It seems this happens only on my local network. Accessing the gui-v2 via https://192.168.x.x/gui-beta/ I can go through all the menus, but the values are not changing/updated. Application version under debug is V0.3.10

![Bildschirmfoto 2024-09-08 um 13 12 03](https://github.com/user-attachments/assets/fbd3a4b9-039f-40f2-a9d5-57f05d3fd50c)

In the VRM Console the GUI v2 is correct

![Bildschirmfoto 2024-09-08 um 13 23 15](https://github.com/user-attachments/assets/8eedfd04-1359-412e-bf3a-acacd697724b)

**Comment by chriadam** [comment] 2024-09-11 03:36
Thanks, I will fix this.

**Comment by chriadam** [comment] 2024-09-11 03:37
Oh, this is a duplicate of issue #1445 - closing.

**Comment by chriadam** [comment] 2024-09-11 03:38
Ah, no, slightly different (but related) case.  Reopening.

**Comment by chriadam** [comment] 2024-09-16 01:37
I was unable to reproduce this issue.  I have merged into main a fix which I think resolves the issue, but without being able to reproduce I am not entirely certain.  Closing this issue for now - please reopen if you can still reproduce with gui-v2 v0.3.11 or later.

**Closed by chriadam** 2024-09-16 01:37 UTC
Labels: medium_prio
