### ISSUE TITLE
Brief tank levels for Black and Waste are inverted

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#680] opened 2024-01-24 21:48 UTC
The same data is shown correctly on the Tanks view.

Reported here: https://community.victronenergy.com/questions/249509/venus-os-v32034-available-for-testing.html?page=2&pageSize=50&sort=oldest

![image](https://github.com/victronenergy/gui-v2/assets/5200296/1595238c-c657-4b9d-9372-85c1d2c473a8)

**Comment by chriadam** [comment] 2024-01-31 06:23
I believe this issue was fixed in https://github.com/victronenergy/gui-v2/pull/685 but we need to confirm.
If this cannot be reproduced with latest release, we can close as fixed.

**Comment by gharshaw** [comment] 2024-02-21 21:29
I just reinstalled with v3.30~6 and the waste and black are still inverted on the brief view

**Comment by blammit** [comment] 2024-02-27 01:37
@gharshaw could you share screenshots of the values in `Settings > Debug > Values > Tank > [tank number]`? Alternatively if you add victron.vrm (at) qinetic.com.au to the list of users in the VRM portal then we can investigate directly.

**Comment by gharshaw** [comment] 2024-02-27 02:42
Sent from my iPhoneOn Feb 26, 2024, at 8:37 PM, Bea Lam ***@***.***> wrote:﻿
@gharshaw could you share screenshots of the values in Settings > Debug > Values > Tank > [tank number]? Alternatively if you add victron.vrm (at) qinetic.com.au to the list of users in the VRM portal then we can investigate directly.

**Comment by blammit** [comment] 2024-02-27 03:13
@gharshaw Thanks! In the values, are there any "Capacity" and "Remaining" values?

**Comment by gharshaw** [comment] 2024-02-27 14:07
![image](https://github.com/victronenergy/gui-v2/assets/79295813/b11a8601-55db-443c-b659-fd3231157aae)
![image](https://github.com/victronenergy/gui-v2/assets/79295813/79b50832-25ad-4080-9338-252b8481f08f)
![image](https://github.com/victronenergy/gui-v2/assets/79295813/596d699d-bb15-4e2f-907c-97f1d788dae9)
![image](https://github.com/victronenergy/gui-v2/assets/79295813/432b3e54-b3e3-4227-b8a3-72485da8a637)
![image](https://github.com/victronenergy/gui-v2/assets/79295813/7ef8ee66-0c90-42a9-bacb-258c76b32bc7)
![image](https://github.com/victronenergy/gui-v2/assets/79295813/f4db6649-598c-4e8d-937b-113d7d32dc99)
![image](https://github.com/victronenergy/gui-v2/assets/79295813/f37d2fc8-df18-4919-b204-894ba2896e92)
![image](https://github.com/victronenergy/gui-v2/assets/79295813/85d7f134-310f-4886-adc0-5baade724dc7)

**Comment by blammit** [comment] 2024-03-12 05:11
> @gharshaw could you share screenshots of the values in `Settings > Debug > Values > Tank > [tank number]`? Alternatively if you add victron.vrm (at) qinetic.com.au to the list of users in the VRM portal then we can investigate directly.

@gharshaw I'm not able to reproduce this locally. Would you be able to add us as a user to your installation on VRM portal so that we can test and verify directly? 

Black and Waste Water should be inverted in colors only, and not in the displayed percentage.

**Comment by gharshaw** [comment] 2024-03-12 15:04
![image](https://github.com/victronenergy/gui-v2/assets/79295813/7051c8c5-1039-4803-9d8d-2993dac96636)
![image](https://github.com/victronenergy/gui-v2/assets/79295813/29375adc-568e-4ed7-87c4-b2d79acdbf1f)
Brief view is showing that Black and Gray Tank are 100% full. The tank view shows that they are 0% full or empty. 0% or empty is the correct state of the tanks. -

**Comment by blammit** [comment] 2024-03-13 07:31
Thanks! Will look further into this.

**Comment by chriadam** [comment] 2024-03-19 03:06
Hi @gharshaw I tried to connect to your installation via VRM today, but it looks like you don't have real-time data updates enabled.  Could you double check that Settings -> VRM Online Portal -> VRM Two Way Communication is enabled, please?

**Comment by gharshaw** [comment] 2024-03-19 12:22
@chriadam 

As you suspected. Two way is now enabled

**Comment by chriadam** [comment] 2024-03-20 10:41
@gharshaw thanks very much, have created PR with the fix now.

**Comment by chriadam** [comment] 2024-03-25 03:05
As per above comment, merged PR then set issue as blocked, low-priority.

**Comment by gharshaw** [comment] 2024-03-28 20:50
@chriadam
Appears to be fixed in v0.2.14 
![Screenshot from 2024-03-28 16-46-56](https://github.com/victronenergy/gui-v2/assets/79295813/58b3b0e0-e990-47b8-aa88-8224babe5d68)
:+1:

**Comment by jpetrell** [comment] 2024-04-10 11:05
What is still needed before the issue can be closed? Can the remaining bit filed as a separate issue?

**Comment by chriadam** [comment] 2024-04-12 03:33
Created issue #937 for the remaining bit, will close this task now.

**Closed by chriadam** 2024-04-12 03:33 UTC
Labels: bug, blocked, low_prio
