### ISSUE TITLE
Tank capacity: wrong values

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#784] opened 2024-02-21 10:58 UTC
Running on Cerbo GX v3.30~7.

When configuring the capacity of a tank in units other than m3, the capacity value is sometimes off. This issue came up earlier when I reproduced other issues with tanks: https://github.com/victronenergy/gui-v2/issues/650. I believe these fixes: https://github.com/victronenergy/gui-v2/pull/685 were included at v3.30~4. 

E.g. I configured a fresh water tank with a capacity of 105l:
![image](https://github.com/victronenergy/gui-v2/assets/38864570/86a791c3-9bd5-4907-ab5a-e822f79d3e31)

But the "Levels" view shows a capacity of 104l instead:
![image](https://github.com/victronenergy/gui-v2/assets/38864570/5e8f9bb2-76cf-4b53-bd95-6fbd42dd797c)

The tank configuration page also shows 105l, but shows 104l when clicked: 
![image](https://github.com/victronenergy/gui-v2/assets/38864570/5975af93-00a5-4a21-ae5a-a84c4ff8ea3e)

**Comment by blammit** [comment] 2024-02-27 01:26
We should check this when https://github.com/victronenergy/gui-v2/pull/745 is merged, as that tweaks the value formatting.

**Comment by jpetrell** [comment] 2024-03-05 19:50
> We should check this when #745 is merged, as that tweaks the value formatting.

The discrepancy may be caused by different rounding behavior. Changes made to the formatting in #745 won't fix the differences seen here as the spinboxes and the button on the spinbox list item don't use the Units API, but both implement custom formatting functions.

Filed https://github.com/victronenergy/gui-v2/issues/831 about moving remaining formatting functions to Units API to avoid unnecessary code duplication and accidental formatting differences.

**Closed** 2024-03-27 07:17 UTC
Labels: medium_prio
