### ISSUE TITLE
Fallback or translations of startpage -> timeout don’t always work?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1665] opened 2024-10-31 05:44 UTC
this is german,

english does work for me. And german too.. so can’t reproduce. And I expect that soon this will be translated - if you can’t reproduce / don’t see something special, then pls close it as non-reproducible. If there are further reports we can always re open it.

![IMG_3352](https://github.com/user-attachments/assets/311942c4-a77b-4a81-97a1-5455f7ed5c63)

**Comment by mpvader** [comment] 2024-10-31 11:49
someone else having it all the time:

![image](https://github.com/user-attachments/assets/89d8d152-3926-49ec-8244-eaad4be1e12d)

**Comment by mpvader** [comment] 2024-10-31 12:47
updated: 
<img width="629" alt="image" src="https://github.com/user-attachments/assets/0555faaf-d3f5-4c20-92d7-8d5bed77c95f">

**Comment by chriadam** [comment] 2024-11-01 08:38
I believe this is (effectively) a duplicate of #1661

**Comment by chriadam** [comment] 2024-11-04 03:21
@dirkjanfaber do you know, was this one also verified to be fixed in v3.51~2?  If so, will close.

**Comment by dirkjanfaber** [comment] 2024-11-04 07:29
Just tested with Romanian and this page. Looks good! Closing. 

![image](https://github.com/user-attachments/assets/7a64b2e8-12b9-4118-a2d9-3b31a3442861)

**Comment by dirkjanfaber** [comment] 2024-11-06 10:25
I think we need to re-open this, @chriadam 

<img width="965" alt="image" src="https://github.com/user-attachments/assets/c4599ff4-e005-4fa3-a4eb-0e8bbcc63989">

Of course it needs to be translated properly, but as long as the translation isn't there yet, it should show the English variant and not the key. 

https://github.com/victronenergy/gui-v2/blob/main/i18n/venus-gui-v2_sv.ts#L8320

**Comment by philipptrenz** [comment] 2024-11-06 14:09
Another find for the Spanish language

See translation here: https://github.com/victronenergy/gui-v2/blob/main/i18n/venus-gui-v2_es.ts#L8437

![Bildschirmfoto 2024-11-06 um 10 03 23](https://github.com/user-attachments/assets/5417ade5-7c45-4ff2-9e08-5c17be514e49)

**Comment by chriadam** [comment] 2024-11-08 02:05
I should be able to simply install the english catalogue as a fallback catalogue, in case some translation is missing from a non-english translation catalogue in some version.

**Comment by mpvader** [comment] 2024-11-12 16:02
Is there more remaining work for this one @chriadam ?

**Comment by chriadam** [comment] 2024-11-13 00:57
No, closing as fixed.

**Closed by chriadam** 2024-11-13 00:57 UTC
Labels: bug, medium_prio
