### ISSUE TITLE
Minor issue: Brief page battery detail only shown when there are no gauges to display

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#542] opened 2023-11-16 17:32 UTC
On a system with any tank sensors, the Brief page shows them as arc gauges. If there are no tank sensors, a battery detail is displayed. 

![Screenshot 2023-11-16 at 8 47 04 AM](https://github.com/victronenergy/gui-v2/assets/58538395/4ccecb95-6acc-4015-b80e-417e95258d2a)

I would like to see this detail along with its arc gauge even with tanks displayed. If this is not always desired, how about if the battery is chosen for Level 4 (the inner most arc).

SOC is on the arc and does not need to be repeated. This could carry over into the "no tanks" display as well.

Battery voltage and current is nice to some but numbers tend to clutter this display. Other places power is shown so this is an inconsistency (if the Power display is set to watts). Could show power as a second arc instead of numbers.

Time to go is probably the most important.

**Comment by chriadam** [comment] 2024-01-31 05:46
There might not be enough space in the middle of the MultiCircularGauge for the battery data to be shown (e.g. if there are 3 tanks as well as the battery).

Marking this as design feedback needed, but low_prio / not for 1.0.0 release.

**Comment by blammit** [comment] 2024-11-08 00:23
Closing as duplicate of https://github.com/victronenergy/gui-v2/issues/1491.

**Closed by blammit** 2024-11-08 00:23 UTC
Labels: Design not ready, low_prio
