### ISSUE TITLE
Solar "State" is wrong

### ISSUE THREAD

**Issue by Next9999** [victronenergy/gui-v2#642] opened 2024-01-06 20:05 UTC
Hello

i notice that the Solar "State" is not the same as the VRM web page

![image](https://github.com/victronenergy/gui-v2/assets/54117519/9e573d67-668e-41f9-ae18-1fd9472f8efa)
![image](https://github.com/victronenergy/gui-v2/assets/54117519/dc151d23-55ca-4405-8feb-744e0cdd9aa5)

**Comment by blammit** [comment] 2024-01-12 05:15
Does the cerbo gui also report a different state?

**Comment by blammit** [comment] 2024-01-24 05:43
@Next9999 can you comment on this? ^

**Comment by chriadam** [comment] 2024-01-31 06:17
Need more info.  Marking as low_prio for now.  If the issue is reproduceable, then it is high prio.

**Comment by blammit** [comment] 2024-02-19 05:28
This is valid, duplicate of https://github.com/victronenergy/gui-v2/issues/762. That has some more details, so I'll close this one.

**Closed by blammit** 2024-02-19 05:28 UTC
Labels: question, low_prio
