### ISSUE TITLE
DVCC "Autoselected" BMS is always "None"

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1025] opened 2024-05-01 08:07 UTC
In the DVCC menu on GUI-v2 (remotely), when setting the controlling BMS to "Autoselected", the selected BMS is "None":
![image](https://github.com/victronenergy/gui-v2/assets/38864570/6304f1e5-c7ba-4e6c-b975-21a3c76729c8)

The path `com.victronenergy.system/ActiveBmsService` is set correctly: `com.victronenergy.battery.socketcan_can0` (or something similar). When the BMS is manually selected, the dbus path does not change, but the selected BMS is filled in correctly on the gui. 

The BMS autoselect feature works as expected on GUI-v1:
![image](https://github.com/victronenergy/gui-v2/assets/38864570/2f7c2beb-34ee-45a9-ba1f-2c839b763fe3)

**Comment by ReinvdZee** [comment] 2024-05-01 11:03
This was reported by a battery manufacturer which recently gained support by Victron. The manufacturer reports a slightly different behavior, which I have not been able to reproduce. In fact, I do not even see the same behavior on his system while he does see it (so he reports).

As given in the issue description, I see "None" as autoselected:
![2](https://github.com/victronenergy/gui-v2/assets/38864570/f227c345-ff18-4fec-8c80-30af523a262f)

The support engineer of the battery manufacturer sees:
![1](https://github.com/victronenergy/gui-v2/assets/38864570/0710bc79-d444-44d3-bb90-5f8446d937c2)

We are both viewing the GUI remotely via VRM. He will report what the physical display shows as well.

**Comment by jpetrell** [comment] 2024-05-02 11:49
This looks like duplicate to #873.

"The problem is that the value of mqtt/system/ActiveBmsService is like a D-Bus service uid (like com.victronenergy.battery.tty0) instead of a MQTT service uid (like mqtt/battery/123). So, the composed uid becomes something like com.victronenergy.battery.tty0/ProductName, which are valid on D-Bus, but not on MQTT."

**Comment by mr-manuel** [comment] 2024-05-02 12:27
Indeed it's the same and https://github.com/victronenergy/gui-v2/pull/1032 did not fix it.

**Comment by jpetrell** [comment] 2024-05-08 20:14
Setting as blocked, @ReinvdZee promised to look into this to see if systemcalc needs changes.

**Comment by ReinvdZee** [comment] 2024-05-13 06:36
@jpetrell, [this commit](https://github.com/victronenergy/dbus-systemcalc-py/commit/8990a0430b8243ec395c6118aec5fd6d35fc00f4) should fix it, it is on the todo but not merged in venus yet.

**Comment by jpetrell** [comment] 2024-05-21 09:04
> [this commit](https://github.com/victronenergy/dbus-systemcalc-py/commit/8990a0430b8243ec395c6118aec5fd6d35fc00f4) should fix it, it is on the todo but not merged in venus yet.

Rein told me that this is Included in the beta release since v3.40~14. Removing blocked status.

**Comment by jpetrell** [comment] 2024-05-23 10:56
Assigning to @blammit, who expressed interested in tackling this and is more familiar with the topic. Shared Python scripts from Rein.

**Closed** 2024-05-28 03:40 UTC
Labels: medium_prio
