### ISSUE TITLE
Bug (?) in vebus battery temperature item

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1354] opened 2024-07-24 05:53 UTC
![IMG_2433](https://github.com/user-attachments/assets/5ac82e77-f126-4b43-870e-faa6849e5ee3)

**Comment by blammit** [comment] 2024-07-25 03:32
Looks to be a duplicate of https://github.com/victronenergy/gui-v2/issues/1257. Closing, but let me know if this is incorrect.

**Closed by blammit** 2024-07-25 03:32 UTC
